###
### MachineDetails Action
###

name: 'MachineDetails'
description: 'Provides machine details for macOS (only)'
author: '(plroebuck)'

## Controls when the workflow will run
on:
  workflow_call:

## Default Values
defaults:
  run:
    shell: bash

inputs:
  show_hardware:
    description: |
      Displays hardware information [true,false]
      Default is `true`.
    default: 'true'
    required: false
  show_software:
    description: |
      Displays software information [true,false]
      Default is `true`.
    default: 'true'
    required: false
  show_environment:
    description: |
      Displays environment variables [true,false]
      Default is `true`.
    default: 'true'
    required: false

runs:
  using: 'composite'
  steps:
    - run: $GITHUB_ACTION_PATH/machinedetails.sh
      shell: bash
      env:
        INPUT_SHOW_HARDWARE:    ${{ inputs.show_hardware }}
        INPUT_SHOW_SOFTWARE:    ${{ inputs.show_software }}
        INPUT_SHOW_ENVIRONMENT: ${{ inputs.show_environment }}
