# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## Default values
defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  simple_test:
    runs-on: macos-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"

  gestalt:
    runs-on: macos-latest
    steps:
      - name: Display system information
        run: |
          echo "::group::System Info"
          sw_vers
          echo "Architecture: $( uname -p )"
          echo "OS: $( uname -sr )"
          echo "Environment:"
          env | sort | sed 's/^/  /'
          echo; echo "CWD: $( pwd )"
          ls -al | sed 's/^/  /'
          echo "::endgroup::"
