###
### SIMPLE
###

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

## Default values
defaults:
  run:
    shell: bash

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  just_a_job_to_do:
    strategy:
      matrix:
        os: [macos-13, macos-14, macos-15]
    runs-on: ${{ matrix.os }}
#    runs-on: macos-latest
    steps:
      - name: Gestalt
        id: vars
        run: |
          echo "prodname=$( sw_vers -productName )" >> $GITHUB_OUTPUT
          echo "prodver=$( sw_vers -productVersion )" >> $GITHUB_OUTPUT
          echo "build=$( sw_vers -buildVersion )" >> $GITHUB_OUTPUT
          echo "arch=$( uname -p )" >> $GITHUB_OUTPUT
          echo "isa=$( uname -m )" >> $GITHUB_OUTPUT
          echo "os=$( uname -sr )" >> $GITHUB_OUTPUT
          echo "applescript=$( osascript -e 'version of AppleScript' )" >> $GITHUB_OUTPUT
          cpubrand="$( sysctl -n machdep.cpu.brand_string | cut -d '-' -f 1 )"
          cpufreq_hz="$( sysctl -n hw.cpufrequency )"
          ghz=1000000000
          echo "cpufreq_ghz=$( echo "scale=2; $cpufreq_hz) / $ghz" | bc )" >> $GITHUB_OUTPUT
          echo "processor=$( echo $cpubrand | sed -e 's/([^][)]*)//g' )" >> $GITHUB_OUTPUT
          
      - name: Display system information
        run: |
          echo "::group::System Info"
          ( sw_vers | tr '\t' '    ' )
          #arch="$( uname -p )"
          #isa="$( uname -m )"
          #os="$( uname -sr )"
          #applescript="$( osascript -e 'version of AppleScript' )"
          #_cpubrand="$( sysctl -n machdep.cpu.brand_string )"
          #_cpufreq="$( sysctl -n hw.cpufrequency )"
          #_ghz=1000000000
          #cpufreq_ghz="$( echo "scale=2; $_cpufreq) / $ghz" | bc )"
          #processor="$( echo $_cpubrand | cut -d '-' -f 1 | sed -e 's/([^][)]*)//g' )"
          printf "%-18s:\t%s"  "Architecture"  ${{ steps.vars.outputs.arch }}
          echo "InstructionSet: ${{ steps.vars.outputs.isa }}"
          echo "OperatingSystem: ${{ steps.vars.outputs.os }}"
          echo "AppleScript: ${{ steps.vars.outputs.applescript }}"
          echo "Processor: ${{ steps.vars.outputs.processor }}"
          echo "ProcessorSpeed: ${{ steps.vars.outputs.cpufreq_ghz}} GHz"
          echo "::endgroup::"

      - name: Display environment
        run: |
          echo "::group::Environment"
          env | sort | sed 's/^/  /'
          echo "::endgroup::"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Display current directory and its contents
        run: |
          echo "::group::CWD (HOME)"
          pwd
          ls -al | sed 's/^/  /'
          cd $GITHUB_WORKSPACE
          echo "::group::CWD (GHWS)"
          pwd
          ls -al | sed 's/^/  /'
          echo "::endgroup::"
